-- REVERT: Restore club stats to what they were before migration 52 (complete_bot_purge)
-- These values are from after migration 51 (security_hardening)

UPDATE clubs SET elo_rating = 1775, total_votes = 742, wins = 367 WHERE name = 'Blockchain at Berkeley';
UPDATE clubs SET elo_rating = 1643, total_votes = 549, wins = 363 WHERE name = 'BerkeleyTime';
UPDATE clubs SET elo_rating = 1643, total_votes = 554, wins = 266 WHERE name = 'Free Ventures';
UPDATE clubs SET elo_rating = 1622, total_votes = 513, wins = 177 WHERE name = 'Innovative Design';
UPDATE clubs SET elo_rating = 1607, total_votes = 523, wins = 253 WHERE name = 'Women on Wall Street';
UPDATE clubs SET elo_rating = 1605, total_votes = 505, wins = 264 WHERE name = 'Mobile Developers of Berkeley';
UPDATE clubs SET elo_rating = 1589, total_votes = 504, wins = 306 WHERE name = 'Berkeley Consulting';
UPDATE clubs SET elo_rating = 1580, total_votes = 569, wins = 342 WHERE name = 'Launchpad';
UPDATE clubs SET elo_rating = 1578, total_votes = 476, wins = 233 WHERE name = 'Camp Kesem Berkeley';
UPDATE clubs SET elo_rating = 1576, total_votes = 570, wins = 289 WHERE name = 'Paws for Mental Health';
UPDATE clubs SET elo_rating = 1572, total_votes = 558, wins = 286 WHERE name = 'Blueprint';
UPDATE clubs SET elo_rating = 1569, total_votes = 525, wins = 275 WHERE name = '180 Degrees Consulting';
UPDATE clubs SET elo_rating = 1557, total_votes = 518, wins = 234 WHERE name = 'CalTV';
UPDATE clubs SET elo_rating = 1555, total_votes = 537, wins = 264 WHERE name = 'Microfinance at Berkeley';
UPDATE clubs SET elo_rating = 1552, total_votes = 518, wins = 242 WHERE name = 'Global Research and Consulting';
UPDATE clubs SET elo_rating = 1553, total_votes = 536, wins = 299 WHERE name = 'Furries at Berkeley';
UPDATE clubs SET elo_rating = 1543, total_votes = 532, wins = 300 WHERE name = 'Codeology';
UPDATE clubs SET elo_rating = 1538, total_votes = 540, wins = 272 WHERE name = 'Berkeley Innovation';
UPDATE clubs SET elo_rating = 1535, total_votes = 453, wins = 205 WHERE name = 'Latinx Business Student Association';
UPDATE clubs SET elo_rating = 1533, total_votes = 539, wins = 281 WHERE name = 'SAAS';
UPDATE clubs SET elo_rating = 1524, total_votes = 541, wins = 253 WHERE name = 'Undergraduate Real Estate Club';
UPDATE clubs SET elo_rating = 1519, total_votes = 529, wins = 303 WHERE name = 'Net Impact Berkeley';
UPDATE clubs SET elo_rating = 1518, total_votes = 645, wins = 273 WHERE name = 'The Berkeley Forum';
UPDATE clubs SET elo_rating = 1516, total_votes = 485, wins = 260 WHERE name = 'UpSync';
UPDATE clubs SET elo_rating = 1516, total_votes = 402, wins = 208 WHERE name = 'Calisthenics Club';
UPDATE clubs SET elo_rating = 1513, total_votes = 542, wins = 278 WHERE name = 'Berkeley Business Society';
UPDATE clubs SET elo_rating = 1508, total_votes = 516, wins = 238 WHERE name = 'Ascend Berkeley';
UPDATE clubs SET elo_rating = 1507, total_votes = 520, wins = 273 WHERE name = 'PlexTech';
UPDATE clubs SET elo_rating = 1504, total_votes = 531, wins = 253 WHERE name = 'Berkeley Finance Club';
UPDATE clubs SET elo_rating = 1497, total_votes = 576, wins = 266 WHERE name = 'BEACN';
UPDATE clubs SET elo_rating = 1497, total_votes = 578, wins = 313 WHERE name = 'DiversaTech';
UPDATE clubs SET elo_rating = 1497, total_votes = 569, wins = 327 WHERE name = 'Product Space';
UPDATE clubs SET elo_rating = 1495, total_votes = 574, wins = 263 WHERE name = 'ANova';
UPDATE clubs SET elo_rating = 1493, total_votes = 579, wins = 282 WHERE name = 'Web Development at Berkeley';
UPDATE clubs SET elo_rating = 1490, total_votes = 545, wins = 294 WHERE name = 'Codebase';
UPDATE clubs SET elo_rating = 1488, total_votes = 553, wins = 289 WHERE name = 'Big Data at Berkeley';
UPDATE clubs SET elo_rating = 1487, total_votes = 577, wins = 263 WHERE name = 'Asian American Association';
UPDATE clubs SET elo_rating = 1486, total_votes = 551, wins = 262 WHERE name = 'SBC Strategy Consulting';
UPDATE clubs SET elo_rating = 1483, total_votes = 550, wins = 238 WHERE name = 'Scholars of Finance';
UPDATE clubs SET elo_rating = 1483, total_votes = 519, wins = 298 WHERE name = 'Venture Capital at Berkeley';
UPDATE clubs SET elo_rating = 1480, total_votes = 506, wins = 223 WHERE name = 'BCEC';
UPDATE clubs SET elo_rating = 1480, total_votes = 528, wins = 239 WHERE name = 'Healthcare Consulting Group';
UPDATE clubs SET elo_rating = 1473, total_votes = 542, wins = 250 WHERE name = 'Nova Consulting';
UPDATE clubs SET elo_rating = 1472, total_votes = 495, wins = 246 WHERE name = 'imagiCal';
UPDATE clubs SET elo_rating = 1472, total_votes = 533, wins = 297 WHERE name = 'Traders at Berkeley';
UPDATE clubs SET elo_rating = 1470, total_votes = 525, wins = 293 WHERE name = 'Berkeley Investment Group';
UPDATE clubs SET elo_rating = 1469, total_votes = 525, wins = 247 WHERE name = 'Berkeley ABA';
UPDATE clubs SET elo_rating = 1469, total_votes = 509, wins = 223 WHERE name = 'Capital Investments at Berkeley';
UPDATE clubs SET elo_rating = 1465, total_votes = 538, wins = 249 WHERE name = 'Undergraduate Marketing Association';
UPDATE clubs SET elo_rating = 1462, total_votes = 530, wins = 284 WHERE name = 'Phoenix Consulting Group';
UPDATE clubs SET elo_rating = 1459, total_votes = 548, wins = 251 WHERE name = 'Delta Consulting';
UPDATE clubs SET elo_rating = 1459, total_votes = 536, wins = 271 WHERE name = 'Next Generation Consulting';
UPDATE clubs SET elo_rating = 1455, total_votes = 401, wins = 157 WHERE name = 'BJJ at Berkeley';
UPDATE clubs SET elo_rating = 1451, total_votes = 566, wins = 270 WHERE name = 'Theta Tau';
UPDATE clubs SET elo_rating = 1446, total_votes = 531, wins = 253 WHERE name = 'Consult Your Community';
UPDATE clubs SET elo_rating = 1439, total_votes = 558, wins = 277 WHERE name = 'Venture Strategy Solutions';
UPDATE clubs SET elo_rating = 1437, total_votes = 571, wins = 277 WHERE name = 'CMG Strategy Consulting';
UPDATE clubs SET elo_rating = 1435, total_votes = 530, wins = 192 WHERE name = 'Alpha Epsilon Zeta';
UPDATE clubs SET elo_rating = 1431, total_votes = 537, wins = 250 WHERE name = 'Blackskies Investments';
UPDATE clubs SET elo_rating = 1430, total_votes = 545, wins = 214 WHERE name = 'Pi Sigma Epsilon';
UPDATE clubs SET elo_rating = 1429, total_votes = 565, wins = 309 WHERE name = 'Voyager Consulting';
UPDATE clubs SET elo_rating = 1428, total_votes = 506, wins = 219 WHERE name = 'Undergraduate Finance Association';
UPDATE clubs SET elo_rating = 1420, total_votes = 509, wins = 223 WHERE name = 'HBSA';
UPDATE clubs SET elo_rating = 1416, total_votes = 497, wins = 201 WHERE name = 'Berkeley PBL';
UPDATE clubs SET elo_rating = 1416, total_votes = 533, wins = 252 WHERE name = 'Beta Alpha Psi';
UPDATE clubs SET elo_rating = 1408, total_votes = 523, wins = 262 WHERE name = 'Data Science Society';
UPDATE clubs SET elo_rating = 1386, total_votes = 551, wins = 311 WHERE name = 'Machine Learning at Berkeley';
UPDATE clubs SET elo_rating = 1334, total_votes = 499, wins = 254 WHERE name = 'The Berkeley Group';
UPDATE clubs SET elo_rating = 1318, total_votes = 602, wins = 270 WHERE name = 'Valley Consulting Group';
UPDATE clubs SET elo_rating = 1269, total_votes = 585, wins = 295 WHERE name = 'Entrepreneurs @ Berkeley';
UPDATE clubs SET elo_rating = 1372, total_votes = 437, wins = 165 WHERE name = 'AI Entrepreneurs at Berkeley';
